<?php

namespace EdgeTariff\EstDutyTax\Model\Attribute\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;

class Material extends AbstractSource
{
    /**
     * Retrieve all options for the material attribute.
     *
     * This method returns an array of countries with their respective codes.
     * It caches the options after the first call to improve performance.
     *
     * @return array
     */
    public function getAllOptions(): array
    {
        // Check if options are already initialized to avoid reinitialization
        if ($this->_options === null) {
            $this->_options = [
            ['label' => __('Select Country'), 'value' => ''],
            ['label' => __('Afghanistan'), 'value' => 'AF'],
            ['label' => __('Albania'), 'value' => 'AL'],
            ['label' => __('Algeria'), 'value' => 'DZ'],
            ['label' => __('Andorra'), 'value' => 'AD'],
            ['label' => __('Angola'), 'value' => 'AO'],
            ['label' => __('Antigua and Barbuda'), 'value' => 'AG'],
            ['label' => __('Argentina'), 'value' => 'AR'],
            ['label' => __('Armenia'), 'value' => 'AM'],
            ['label' => __('Aruba'), 'value' => 'AW'],
            ['label' => __('Australia'), 'value' => 'AU'],
            ['label' => __('Austria'), 'value' => 'AT'],
            ['label' => __('Azerbaijan'), 'value' => 'AZ'],
            ['label' => __('Bahamas'), 'value' => 'BS'],
            ['label' => __('Bahrain'), 'value' => 'BH'],
            ['label' => __('Bangladesh'), 'value' => 'BD'],
            ['label' => __('Barbados'), 'value' => 'BB'],
            ['label' => __('Belarus'), 'value' => 'BY'],
            ['label' => __('Belgium'), 'value' => 'BE'],
            ['label' => __('Belize'), 'value' => 'BZ'],
            ['label' => __('Benin'), 'value' => 'BJ'],
            ['label' => __('Bermuda'), 'value' => 'BM'],
            ['label' => __('Bhutan'), 'value' => 'BT'],
            ['label' => __('Bolivia'), 'value' => 'BO'],
            ['label' => __('Caribbean Netherlands'), 'value' => 'BQ'],
            ['label' => __('Bosnia and Herzegovina'), 'value' => 'BA'],
            ['label' => __('Botswana'), 'value' => 'BW'],
            ['label' => __('Brazil'), 'value' => 'BR'],
            ['label' => __('Brunei Darussalam'), 'value' => 'BN'],
            ['label' => __('Bulgaria'), 'value' => 'BG'],
            ['label' => __('Burkina Faso'), 'value' => 'BF'],
            ['label' => __('Burundi'), 'value' => 'BI'],
            ['label' => __('Cabo Verde'), 'value' => 'CV'],
            ['label' => __('Cambodia'), 'value' => 'KH'],
            ['label' => __('Cameroon'), 'value' => 'CM'],
            ['label' => __('Canada'), 'value' => 'CA'],
            ['label' => __('Central African Republic'), 'value' => 'CF'],
            ['label' => __('Chad'), 'value' => 'TD'],
            ['label' => __('Chile'), 'value' => 'CL'],
            ['label' => __('China'), 'value' => 'CN'],
            ['label' => __('Colombia'), 'value' => 'CO'],
            ['label' => __('Democratic Republic of the Congo'), 'value' => 'CD'],
            ['label' => __('Republic of the Congo'), 'value' => 'CG'],
            ['label' => __('Cook Islands'), 'value' => 'CK'],
            ['label' => __('Costa Rica'), 'value' => 'CR'],
            ['label' => __('Cote d\'Ivoire'), 'value' => 'CI'],
            ['label' => __('Croatia'), 'value' => 'HR'],
            ['label' => __('Curacao'), 'value' => 'CW'],
            ['label' => __('Cyprus'), 'value' => 'CY'],
            ['label' => __('Czechia'), 'value' => 'CZ'],
            ['label' => __('Denmark'), 'value' => 'DK'],
            ['label' => __('Djibouti'), 'value' => 'DJ'],
            ['label' => __('Dominica'), 'value' => 'DM'],
            ['label' => __('Dominican Republic'), 'value' => 'DO'],
            ['label' => __('Ecuador'), 'value' => 'EC'],
            ['label' => __('Egypt'), 'value' => 'EG'],
            ['label' => __('El Salvador'), 'value' => 'SV'],
            ['label' => __('Equatorial Guinea'), 'value' => 'GQ'],
            ['label' => __('Estonia'), 'value' => 'EE'],
            ['label' => __('Eswatini'), 'value' => 'SZ'],
            ['label' => __('Ethiopia'), 'value' => 'ET'],
            ['label' => __('Faroe Islands'), 'value' => 'FO'],
            ['label' => __('Fiji'), 'value' => 'FJ'],
            ['label' => __('Finland'), 'value' => 'FI'],
            ['label' => __('France'), 'value' => 'FR'],
            ['label' => __('Gabon'), 'value' => 'GA'],
            ['label' => __('Gambia'), 'value' => 'GM'],
            ['label' => __('Georgia'), 'value' => 'GE'],
            ['label' => __('Germany'), 'value' => 'DE'],
            ['label' => __('Ghana'), 'value' => 'GH'],
            ['label' => __('Gibraltar'), 'value' => 'GI'],
            ['label' => __('Greece'), 'value' => 'GR'],
            ['label' => __('Greenland'), 'value' => 'GL'],
            ['label' => __('Grenada'), 'value' => 'GD'],
            ['label' => __('Guadeloupe'), 'value' => 'GP'],
            ['label' => __('Guam'), 'value' => 'GU'],
            ['label' => __('Guatemala'), 'value' => 'GT'],
            ['label' => __('Guinea'), 'value' => 'GN'],
            ['label' => __('Guinea-Bissau'), 'value' => 'GW'],
            ['label' => __('Guyana'), 'value' => 'GY'],
            ['label' => __('Haiti'), 'value' => 'HT'],
            ['label' => __('Honduras'), 'value' => 'HN'],
            ['label' => __('Hong Kong'), 'value' => 'HK'],
            ['label' => __('Hungary'), 'value' => 'HU'],
            ['label' => __('Iceland'), 'value' => 'IS'],
            ['label' => __('India'), 'value' => 'IN'],
            ['label' => __('Indonesia'), 'value' => 'ID'],
            ['label' => __('Ireland'), 'value' => 'IE'],
            ['label' => __('Israel'), 'value' => 'IL'],
            ['label' => __('Italy'), 'value' => 'IT'],
            ['label' => __('Jamaica'), 'value' => 'JM'],
            ['label' => __('Japan'), 'value' => 'JP'],
            ['label' => __('Jordan'), 'value' => 'JO'],
            ['label' => __('Kazakhstan'), 'value' => 'KZ'],
            ['label' => __('Kenya'), 'value' => 'KE'],
            ['label' => __('Korea'), 'value' => 'KR'],
            ['label' => __('Kuwait'), 'value' => 'KW'],
            ['label' => __('Kyrgyzstan'), 'value' => 'KG'],
            ['label' => __('Latvia'), 'value' => 'LV'],
            ['label' => __('Lebanon'), 'value' => 'LB'],
            ['label' => __('Lesotho'), 'value' => 'LS'],
            ['label' => __('Liberia'), 'value' => 'LR'],
            ['label' => __('Libya'), 'value' => 'LY'],
            ['label' => __('Lithuania'), 'value' => 'LT'],
            ['label' => __('Luxembourg'), 'value' => 'LU'],
            ['label' => __('Macao'), 'value' => 'MO'],
            ['label' => __('Madagascar'), 'value' => 'MG'],
            ['label' => __('Malawi'), 'value' => 'MW'],
            ['label' => __('Malaysia'), 'value' => 'MY'],
            ['label' => __('Maldives'), 'value' => 'MV'],
            ['label' => __('Mali'), 'value' => 'ML'],
            ['label' => __('Malta'), 'value' => 'MT'],
            ['label' => __('Marshall Islands'), 'value' => 'MH'],
            ['label' => __('Mauritania'), 'value' => 'MR'],
            ['label' => __('Mauritius'), 'value' => 'MU'],
            ['label' => __('Mexico'), 'value' => 'MX'],
            ['label' => __('Federated States of Micronesia'), 'value' => 'FM'],
            ['label' => __('Moldova'), 'value' => 'MD'],
            ['label' => __('Mongolia'), 'value' => 'MN'],
            ['label' => __('Montenegro'), 'value' => 'ME'],
            ['label' => __('Montserrat'), 'value' => 'MS'],
            ['label' => __('Morocco'), 'value' => 'MA'],
            ['label' => __('Mozambique'), 'value' => 'MZ'],
            ['label' => __('Myanmar'), 'value' => 'MM'],
            ['label' => __('Namibia'), 'value' => 'NA'],
            ['label' => __('Nepal'), 'value' => 'NP'],
            ['label' => __('Netherlands'), 'value' => 'NL'],
            ['label' => __('New Zealand'), 'value' => 'NZ'],
            ['label' => __('Nicaragua'), 'value' => 'NI'],
            ['label' => __('Niger'), 'value' => 'NE'],
            ['label' => __('Nigeria'), 'value' => 'NG'],
            ['label' => __('Northern Mariana Islands'), 'value' => 'MP'],
            ['label' => __('Norway'), 'value' => 'NO'],
            ['label' => __('Oman'), 'value' => 'OM'],
            ['label' => __('Pakistan'), 'value' => 'PK'],
            ['label' => __('Palau'), 'value' => 'PW'],
            ['label' => __('Palestine'), 'value' => 'PS'],
            ['label' => __('Panama'), 'value' => 'PA'],
            ['label' => __('Papua New Guinea'), 'value' => 'PG'],
            ['label' => __('Paraguay'), 'value' => 'PY'],
            ['label' => __('Peru'), 'value' => 'PE'],
            ['label' => __('Philippines'), 'value' => 'PH'],
            ['label' => __('Poland'), 'value' => 'PL'],
            ['label' => __('Portugal'), 'value' => 'PT'],
            ['label' => __('Qatar'), 'value' => 'QA'],
            ['label' => __('Republic of North Macedonia'), 'value' => 'MK'],
            ['label' => __('Romania'), 'value' => 'RO'],
            ['label' => __('Russian Federation'), 'value' => 'RU'],
            ['label' => __('Rwanda'), 'value' => 'RW'],
            ['label' => __('Saint Kitts and Nevis'), 'value' => 'KN'],
            ['label' => __('Saint Lucia'), 'value' => 'LC'],
            ['label' => __('Saint Martin'), 'value' => 'MF'],
            ['label' => __('Saint Vincent and the Grenadines'), 'value' => 'VC'],
            ['label' => __('Samoa'), 'value' => 'WS'],
            ['label' => __('Saudi Arabia'), 'value' => 'SA'],
            ['label' => __('Senegal'), 'value' => 'SN'],
            ['label' => __('Serbia'), 'value' => 'RS'],
            ['label' => __('Seychelles'), 'value' => 'SC'],
            ['label' => __('Singapore'), 'value' => 'SG'],
            ['label' => __('Sint Maarten'), 'value' => 'SX'],
            ['label' => __('Slovakia'), 'value' => 'SK'],
            ['label' => __('Slovenia'), 'value' => 'SI'],
            ['label' => __('South Africa'), 'value' => 'ZA'],
            ['label' => __('Spain'), 'value' => 'ES'],
            ['label' => __('Sri Lanka'), 'value' => 'LK'],
            ['label' => __('Suriname'), 'value' => 'SR'],
            ['label' => __('Sweden'), 'value' => 'SE'],
            ['label' => __('Switzerland'), 'value' => 'CH'],
            ['label' => __('Taiwan'), 'value' => 'TW'],
            ['label' => __('Tajikistan'), 'value' => 'TJ'],
            ['label' => __('Tanzania'), 'value' => 'TZ'],
            ['label' => __('Thailand'), 'value' => 'TH'],
            ['label' => __('Timor-Leste'), 'value' => 'TL'],
            ['label' => __('Togo'), 'value' => 'TG'],
            ['label' => __('Tonga'), 'value' => 'TO'],
            ['label' => __('Trinidad and Tobago'), 'value' => 'TT'],
            ['label' => __('Tunisia'), 'value' => 'TN'],
            ['label' => __('Turkey'), 'value' => 'TR'],
            ['label' => __('Turkmenistan'), 'value' => 'TM'],
            ['label' => __('Uganda'), 'value' => 'UG'],
            ['label' => __('Ukraine'), 'value' => 'UA'],
            ['label' => __('United Arab Emirates'), 'value' => 'AE'],
            ['label' => __('United Kingdom'), 'value' => 'GB'],
            ['label' => __('United States'), 'value' => 'US'],
            ['label' => __('Uruguay'), 'value' => 'UY'],
            ['label' => __('Uzbekistan'), 'value' => 'UZ'],
            ['label' => __('Vanuatu'), 'value' => 'VU'],
            ['label' => __('Venezuela'), 'value' => 'VE'],
            ['label' => __('Viet Nam'), 'value' => 'VN'],
            ['label' => __('Wallis and Futuna'), 'value' => 'WF'],
            ['label' => __('Yemen'), 'value' => 'YE'],
            ['label' => __('Zambia'), 'value' => 'ZM'],
            ['label' => __('Zimbabwe'), 'value' => 'ZW'],
            ['label' => __('Anguilla'), 'value' => 'AI'],
            ['label' => __('Canary Islands'), 'value' => 'IC'],
            ['label' => __('Cayman Islands'), 'value' => 'KY'],
            ['label' => __('East Timor'), 'value' => 'TP'],
            ['label' => __('European Union'), 'value' => 'EU'],
            ['label' => __('French Polynesia'), 'value' => 'PF'],
            ['label' => __('Guernsey'), 'value' => 'GG'],
            ['label' => __('Iraq'), 'value' => 'IQ'],
            ['label' => __('Jersey'), 'value' => 'JE'],
            ['label' => __('Kosovo'), 'value' => 'XK'],
            ['label' => __('Laos'), 'value' => 'LA'],
            ['label' => __('Martinique'), 'value' => 'MQ'],
            ['label' => __('New Caledonia'), 'value' => 'NC'],
            ['label' => __('Puerto Rico'), 'value' => 'PR'],
            ['label' => __('Sierra Leone'), 'value' => 'SL'],
            ['label' => __('St Barts'), 'value' => 'BL'],
            ['label' => __('Turks and Caicos Islands'), 'value' => 'TC'],
            ['label' => __('Virgin Islands (BC)'), 'value' => 'VG'],
            ['label' => __('Virgin Islands (US)'), 'value' => 'VI']
            ];
        }
        return $this->_options;
    }
}
