<?php
// Get the Escaper instance
/** @var \Magento\Framework\Escaper $escaper */
$escaper = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Escaper::class);

// Get the Data helper instance
/** @var \EdgeCTP\EstDutyTax\Helper\Data $helper */
$helper = \Magento\Framework\App\ObjectManager::getInstance()->get(\EdgeTariff\EstDutyTax\Helper\Data::class);

// Get the base URL of the store using the helper method
$baseUrl = rtrim($escaper->escapeUrl($helper->getStoreBaseUrl()), '/');

// Escape the WTT_BASE_URL and base URL using the Escaper
$wttUrl = $escaper->escapeUrl($helper->getWttBaseUrl());
$shopUrl = $baseUrl;
?>

<iframe id="if1" width="100%" style="visibility:visible;height:100vh;"src="
<?= $escaper->escapeUrl($wttUrl); ?>/Magento/RPS.aspx?action=ShowDashboard&code=0907a61c0c8d55e99db179b68161bc00
&SourceStoreName=<?= $escaper->escapeHtmlAttr($baseUrl); ?>"></iframe>
