<?php
// Get the Escaper instance
/** @var \Magento\Framework\Escaper $escaper */
$escaper = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Escaper::class);

// Get the Data helper instance
/** @var \EdgeCTP\EstDutyTax\Helper\Data $helper */
$helper = \Magento\Framework\App\ObjectManager::getInstance()->get(\EdgeTariff\EstDutyTax\Helper\Data::class);

// Get product details and base URL
$productDetails = $block->getProductDetails();

// Get the base URL of the store using the helper method
$baseUrl = rtrim($escaper->escapeUrl($helper->getStoreBaseUrl()), '/');
//$parsedUrl = parse_url($baseUrl);
//$baseUrl = $parsedUrl['scheme'] . '://' . $parsedUrl['host'];

// Extract and escape product details
$productId = $escaper->escapeHtmlAttr($productDetails['product_id']);
// $productName = $escaper->escapeUrl($productDetails['product_name']);
$productName = $productDetails['product_name'];
$hs6Code = $escaper->escapeHtmlAttr($productDetails['hs6code']);
$countryOfOrigin = $escaper->escapeHtmlAttr($productDetails['country_of_origin']);
$productUnitPrice = $escaper->escapeHtmlAttr($productDetails['product_unit_price']);

// Escape and encode values
// Escape the WTT_BASE_URL and base URL using the Escaper
$wttUrl = $escaper->escapeUrl($helper->getWttBaseUrl());
// $encodedProductName = urlencode($productName);
$cleanName = html_entity_decode($productName);

// Build the iframe src attribute
$iframeSrc = $wttUrl . "/Magento/RPS.aspx?action=RequestPPC" .
    "&ProductId=" . $productId .
    "&code=0907a61c0c8d55e99db179b68161bc00" .
    "&SourceStoreName=" . $baseUrl .
    "&product_name=" . $cleanName .
    "&ProductUnitPrice=" . $productUnitPrice .
    "&Wttcounty=" . $countryOfOrigin .
    "&Wtths6code=" . $hs6Code;
?>

<iframe id='if1' width='100%' height='1000px' style='visibility:visible' 
src='<?= $escaper->escapeHtmlAttr($iframeSrc); ?>'></iframe>
