<?php
use Laminas\Uri\UriFactory;

// Get the Escaper instance
/** @var \Magento\Framework\Escaper $escaper */
$escaper = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Escaper::class);

// Get the Data helper instance
/** @var \EdgeCTP\EstDutyTax\Helper\Data $helper */
$helper = \Magento\Framework\App\ObjectManager::getInstance()->get(\EdgeTariff\EstDutyTax\Helper\Data::class);

// Get dynamic values
$action = "ShowRPS";
$orderId = $escaper->escapeHtmlAttr($block->getData('order_id'));
$userId = $escaper->escapeHtmlAttr($block->getData('user_id')); // Assuming 'user_id' is the correct key
// Get the base URL of the store using the helper method
$baseUrl = $escaper->escapeUrl($helper->getStoreBaseUrl());
// Use Laminas\Uri to parse the URL
$uri = UriFactory::factory($baseUrl);

$baseUrl = $uri->getScheme() . '://' . $uri->getHost();

// Escape and encode values
$wttUrl = $wttUrl = $escaper->escapeUrl($helper->getWttBaseUrl());
$encodedAction = urlencode($action);
$encodedOrderId = urlencode($orderId);
$encodedUserId = urlencode($userId);
$encodedSiteUrl = urlencode($baseUrl);

// Build the iframe src attribute
$iframeSrc = $wttUrl . "/Magento/RPS.aspx?action=" . $encodedAction .
    "&UserId=" . $encodedUserId .
    "&SourceStoreName=" . $encodedSiteUrl;
?>

<iframe id='if1' width='100%' height='1000px' style='visibility:visible' 
src='<?= $escaper->escapeHtmlAttr($iframeSrc);?> '></iframe>
